
language: node_js

node_js:
  - 6
  - 7

sudo: false

script:
  - npm install
  - npm run build
  - npm test

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
