window.esdocSearchIndex = [
  [
    "createrest/lib~maker",
    "class/lib/index.js~Maker.html",
    "<span>Maker</span> <span class=\"search-result-import-path\">createrest/lib</span>",
    "class"
  ],
  [
    "createrest/lib~createrest",
    "function/index.html#static-function-createRest",
    "<span>createRest</span> <span class=\"search-result-import-path\">createrest/lib</span>",
    "function"
  ],
  [
    "createrest/lib/symbol~createrestinstancesymbol",
    "variable/index.html#static-variable-createRestInstanceSymbol",
    "<span>createRestInstanceSymbol</span> <span class=\"search-result-import-path\">createrest/lib/symbol</span>",
    "variable"
  ],
  [
    "createrest/lib/flatten~flattenroutes",
    "function/index.html#static-function-flattenRoutes",
    "<span>flattenRoutes</span> <span class=\"search-result-import-path\">createrest/lib/flatten</span>",
    "function"
  ],
  [
    "createrest/lib~iscreaterestinstance",
    "function/index.html#static-function-isCreateRestInstance",
    "<span>isCreateRestInstance</span> <span class=\"search-result-import-path\">createrest/lib</span>",
    "function"
  ],
  [
    "createrest/lib/printer~printroutes",
    "function/index.html#static-function-printRoutes",
    "<span>printRoutes</span> <span class=\"search-result-import-path\">createrest/lib/printer</span>",
    "function"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/.external-nodejs.js~http~clientrequest",
    "https://nodejs.org/dist/latest/docs/api/http.html#http_class_http_clientrequest",
    "lib/.external-nodejs.js~http~ClientRequest",
    "external"
  ],
  [
    "lib/flatten.js",
    "file/lib/flatten.js.html",
    "lib/flatten.js",
    "file"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/index.js~crudcontroller",
    "typedef/index.html#static-typedef-CrudController",
    "lib/index.js~CrudController",
    "typedef"
  ],
  [
    "lib/index.js~maker#aftereach",
    "class/lib/index.js~Maker.html#instance-method-afterEach",
    "lib/index.js~Maker#afterEach",
    "method"
  ],
  [
    "lib/index.js~maker#beforeeach",
    "class/lib/index.js~Maker.html#instance-method-beforeEach",
    "lib/index.js~Maker#beforeEach",
    "method"
  ],
  [
    "lib/index.js~maker#build",
    "class/lib/index.js~Maker.html#instance-method-build",
    "lib/index.js~Maker#build",
    "method"
  ],
  [
    "lib/index.js~maker#constructor",
    "class/lib/index.js~Maker.html#instance-constructor-constructor",
    "lib/index.js~Maker#constructor",
    "method"
  ],
  [
    "lib/index.js~maker#crud",
    "class/lib/index.js~Maker.html#instance-method-crud",
    "lib/index.js~Maker#crud",
    "method"
  ],
  [
    "lib/index.js~maker#delete",
    "class/lib/index.js~Maker.html#instance-method-delete",
    "lib/index.js~Maker#delete",
    "method"
  ],
  [
    "lib/index.js~maker#get",
    "class/lib/index.js~Maker.html#instance-method-get",
    "lib/index.js~Maker#get",
    "method"
  ],
  [
    "lib/index.js~maker#local",
    "class/lib/index.js~Maker.html#instance-method-local",
    "lib/index.js~Maker#local",
    "method"
  ],
  [
    "lib/index.js~maker#patch",
    "class/lib/index.js~Maker.html#instance-method-patch",
    "lib/index.js~Maker#patch",
    "method"
  ],
  [
    "lib/index.js~maker#post",
    "class/lib/index.js~Maker.html#instance-method-post",
    "lib/index.js~Maker#post",
    "method"
  ],
  [
    "lib/index.js~maker#put",
    "class/lib/index.js~Maker.html#instance-method-put",
    "lib/index.js~Maker#put",
    "method"
  ],
  [
    "lib/index.js~maker#resources",
    "class/lib/index.js~Maker.html#instance-method-resources",
    "lib/index.js~Maker#resources",
    "method"
  ],
  [
    "lib/index.js~maker#scope",
    "class/lib/index.js~Maker.html#instance-method-scope",
    "lib/index.js~Maker#scope",
    "method"
  ],
  [
    "lib/index.js~maker.crudoptions",
    "typedef/index.html#static-typedef-crudOptions",
    "lib/index.js~Maker.crudOptions",
    "typedef"
  ],
  [
    "lib/index.js~maker.resourcesoptions",
    "typedef/index.html#static-typedef-resourcesOptions",
    "lib/index.js~Maker.resourcesOptions",
    "typedef"
  ],
  [
    "lib/index.js~resourcescontroller",
    "typedef/index.html#static-typedef-ResourcesController",
    "lib/index.js~ResourcesController",
    "typedef"
  ],
  [
    "lib/index.js~restroutes",
    "typedef/index.html#static-typedef-RestRoutes",
    "lib/index.js~RestRoutes",
    "typedef"
  ],
  [
    "lib/printer.js",
    "file/lib/printer.js.html",
    "lib/printer.js",
    "file"
  ],
  [
    "lib/symbol.js",
    "file/lib/symbol.js.html",
    "lib/symbol.js",
    "file"
  ]
]