export get from './get'
export post from './post'
export put from './put'
export patch from './patch'
export destroy from './destroy'
export resources from './resources'
// export resource from './resource'
export scope from './scope'
// export member from './member'
export childs from './childs'
